In [6]:
import pandas as pd
import numpy as np

In [10]:
# Set a random seed for reproducibility
np.random.seed(42)

# Define the number of records to create
num_records = 100

# Create sample data
car_makes = ['Toyota', 'Honda', 'Ford', 'BMW', 'Mercedes', 'Audi', 'Chevrolet', 'Nissan', 'Hyundai', 'Kia']
car_models = {
    'Toyota': ['Camry', 'Corolla', 'RAV4', 'Highlander', 'Tacoma'],
    'Honda': ['Civic', 'Accord', 'CR-V', 'Pilot', 'Odyssey'],
    'Ford': ['F-150', 'Escape', 'Explorer', 'Mustang', 'Focus'],
    'BMW': ['3 Series', '5 Series', 'X3', 'X5', '7 Series'],
    'Mercedes': ['C-Class', 'E-Class', 'GLC', 'GLE', 'S-Class'],
    'Audi': ['A3', 'A4', 'Q5', 'Q7', 'A6'],
    'Chevrolet': ['Silverado', 'Equinox', 'Malibu', 'Traverse', 'Tahoe'],
    'Nissan': ['Altima', 'Rogue', 'Sentra', 'Pathfinder', 'Murano'],
    'Hyundai': ['Elantra', 'Tucson', 'Santa Fe', 'Sonata', 'Kona'],
    'Kia': ['Forte', 'Sportage', 'Sorento', 'Telluride', 'Soul']
}

# Generate random data
makes = np.random.choice(car_makes, num_records)
models = [np.random.choice(car_models[make]) for make in makes]
years = np.random.randint(2010, 2024, num_records)
mileage = np.random.randint(1000, 150000, num_records)
conditions = np.random.choice(['Excellent', 'Good', 'Fair', 'Poor'], num_records, p=[0.3, 0.4, 0.2, 0.1])

# Generate prices based on make, year, and mileage
base_prices = {
    'Toyota': 25000, 'Honda': 24000, 'Ford': 27000, 'BMW': 45000, 
    'Mercedes': 50000, 'Audi': 42000, 'Chevrolet': 30000, 
    'Nissan': 23000, 'Hyundai': 22000, 'Kia': 21000
}

prices = []
for i in range(num_records):
    make = makes[i]
    year = years[i]
    miles = mileage[i]
    condition = conditions[i]
    
    # Base price for the make
    price = base_prices[make]
    
    # Adjust for year (newer cars cost more)
    price += (year - 2010) * 1000
    
    # Adjust for mileage (higher mileage reduces price)
    price -= (miles / 10000) * 1000
    
    # Adjust for condition
    condition_factors = {'Excellent': 1.1, 'Good': 1.0, 'Fair': 0.9, 'Poor': 0.7}
    price *= condition_factors[condition]
    
    # Add some random variation
    price *= np.random.uniform(0.9, 1.1)
    
    prices.append(max(round(price, 2), 5000))  # Ensure minimum price of $5000

# Create DataFrame
car_price = pd.DataFrame({
    'Make': makes,
    'Model': models,
    'Year': years,
    'Mileage': mileage,
    'Condition': conditions,
    'Price': prices
})

# Save to CSV
csv_filename = 'car_pricing_data.csv'
car_price.to_csv(csv_filename, index=False)

print(f"CSV file '{csv_filename}' created successfully with {num_records} records.")

# Display the first few rows of the dataset
car_price

CSV file 'car_pricing_data.csv' created successfully with 100 records.

         Make     Model  Year  Mileage  Condition     Price
0   Chevrolet  Traverse  2010    20830  Excellent  31337.87
1         BMW  5 Series  2018   149501       Poor  26921.01
2      Nissan    Altima  2021   138965       Good  18948.47
3    Mercedes   S-Class  2020   117381  Excellent  57825.61
4   Chevrolet    Malibu  2015    48333  Excellent  35050.24
..        ...       ...   ...      ...        ...       ...
95        Kia     Forte  2010     9308       Good  18394.42
96    Hyundai      Kona  2021     6949       Good  34738.72
97  Chevrolet  Traverse  2020   133222       Good  26953.05
98    Hyundai    Tucson  2012   101235  Excellent  14240.95
99     Nissan    Sentra  2015    75740  Excellent  22069.81

[100 rows x 6 columns]

In [11]:
print(car_data)

         Make     Model  Year  Mileage  Condition     Price
0   Chevrolet  Traverse  2010    20830  Excellent  31337.87
1         BMW  5 Series  2018   149501       Poor  26921.01
2      Nissan    Altima  2021   138965       Good  18948.47
3    Mercedes   S-Class  2020   117381  Excellent  57825.61
4   Chevrolet    Malibu  2015    48333  Excellent  35050.24
..        ...       ...   ...      ...        ...       ...
95        Kia     Forte  2010     9308       Good  18394.42
96    Hyundai      Kona  2021     6949       Good  34738.72
97  Chevrolet  Traverse  2020   133222       Good  26953.05
98    Hyundai    Tucson  2012   101235  Excellent  14240.95
99     Nissan    Sentra  2015    75740  Excellent  22069.81

[100 rows x 6 columns]

In [17]:
df=pd.DataFrame(car_price)

In [18]:
df

         Make     Model  Year  Mileage  Condition     Price
0   Chevrolet  Traverse  2010    20830  Excellent  31337.87
1         BMW  5 Series  2018   149501       Poor  26921.01
2      Nissan    Altima  2021   138965       Good  18948.47
3    Mercedes   S-Class  2020   117381  Excellent  57825.61
4   Chevrolet    Malibu  2015    48333  Excellent  35050.24
..        ...       ...   ...      ...        ...       ...
95        Kia     Forte  2010     9308       Good  18394.42
96    Hyundai      Kona  2021     6949       Good  34738.72
97  Chevrolet  Traverse  2020   133222       Good  26953.05
98    Hyundai    Tucson  2012   101235  Excellent  14240.95
99     Nissan    Sentra  2015    75740  Excellent  22069.81

[100 rows x 6 columns]

In [19]:
df.columns

Index(['Make', 'Model', 'Year', 'Mileage', 'Condition', 'Price'], dtype='object')

In [21]:
df.describe()

              Year        Mileage         Price
count   100.000000     100.000000    100.000000
mean   2015.620000   77173.160000  27331.329600
std       4.037151   44083.012574  12258.566302
min    2010.000000    3368.000000   8501.560000
25%    2012.000000   36289.750000  18353.932500
50%    2015.500000   83412.000000  25187.685000
75%    2018.250000  114897.000000  34019.305000
max    2023.000000  149501.000000  60736.030000

In [26]:
df[df['Mileage'] >= 17000 ]

         Make     Model  Year  Mileage  Condition     Price
0   Chevrolet  Traverse  2010    20830  Excellent  31337.87
1         BMW  5 Series  2018   149501       Poor  26921.01
2      Nissan    Altima  2021   138965       Good  18948.47
3    Mercedes   S-Class  2020   117381  Excellent  57825.61
4   Chevrolet    Malibu  2015    48333  Excellent  35050.24
..        ...       ...   ...      ...        ...       ...
93        Kia   Sorento  2012    91852       Good  14039.05
94  Chevrolet    Malibu  2010    33217       Poor  20240.42
97  Chevrolet  Traverse  2020   133222       Good  26953.05
98    Hyundai    Tucson  2012   101235  Excellent  14240.95
99     Nissan    Sentra  2015    75740  Excellent  22069.81

[88 rows x 6 columns]

In [29]:
df.head(17)

         Make      Model  Year  Mileage  Condition     Price
0   Chevrolet   Traverse  2010    20830  Excellent  31337.87
1         BMW   5 Series  2018   149501       Poor  26921.01
2      Nissan     Altima  2021   138965       Good  18948.47
3    Mercedes    S-Class  2020   117381  Excellent  57825.61
4   Chevrolet     Malibu  2015    48333  Excellent  35050.24
5         Kia  Telluride  2022   135508  Excellent  19740.20
6        Ford   Explorer  2012    77213       Poor  16178.84
7   Chevrolet     Malibu  2013   137967       Good  21024.73
8      Nissan     Altima  2021    31746       Good  33882.86
9    Mercedes        GLC  2020    50377       Good  50080.23
10        BMW   7 Series  2013    55045       Good  44510.09
11     Nissan     Sentra  2012    98888       Fair  13724.97
12     Nissan     Altima  2019   108455  Excellent  24227.89
13       Ford      Focus  2012   137672       Good  16660.58
14       Audi         A4  2012    94179  Excellent  39470.85
15   Mercedes        GLC  2013    46714  Excellent  56744.16
16      Honda      Civic  2016   103946       Good  21043.92

In [31]:
df.tail(10)

         Make     Model  Year  Mileage  Condition     Price
90       Ford   Mustang  2017   104481  Excellent  23711.21
91     Toyota   Corolla  2017   113566       Poor  15723.55
92   Mercedes       GLE  2016    26945       Fair  47175.10
93        Kia   Sorento  2012    91852       Good  14039.05
94  Chevrolet    Malibu  2010    33217       Poor  20240.42
95        Kia     Forte  2010     9308       Good  18394.42
96    Hyundai      Kona  2021     6949       Good  34738.72
97  Chevrolet  Traverse  2020   133222       Good  26953.05
98    Hyundai    Tucson  2012   101235  Excellent  14240.95
99     Nissan    Sentra  2015    75740  Excellent  22069.81